services:
  db:
    container_name: artico-db
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_datas:/var/lib/postgresql
    networks:
      - connectDB

  backend:
    container_name: artico-backend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - connectDB

  # server:
  #   container_name: server
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - backend
  #   restart: always
  #   networks:
  #     - connectDB

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: >
  #     certonly --webroot
  #     --webroot-path=/var/www/certbot
  #     --email ton@email.com
  #     --agree-tos
  #     --no-eff-email
  #     -d valentinneff.dev
  #     -d www.valentinneff.dev

volumes:
  postgres_datas:

networks:
  connectDB:
    driver: bridge
